"""
step02_load_psr.py  —  Load the binary Permanently Shadowed Region (PSR) mask.

Purpose
-------
Load a pre-rasterised binary PSR mask (uint8 GeoTIFF, 1=PSR / 0=non-PSR)
co-registered with the LOLA DEM, OR rasterise a PSR shapefile onto the DEM
grid on the fly.

Scientific role
---------------
The PSR mask is the first of two conditions for DPSR classification
(O'Brien & Byrne 2022, Definition in Sec. 2.3):

    DPSR = PSR  ∩  { no visible non-PSR terrain in any azimuth direction }

Pixels with psr_mask == 0 are, by definition, candidates for non-PSR terrain
that a DPSR candidate must NOT be able to see.  This mask is therefore used
as BOTH an input filter (only PSR pixels are processed) AND the visibility
target (looking for psr_mask == 0 along each ray).

Inputs
------
PSR_MASK_TIF : Path — pre-rasterised PSR mask (uint8 GeoTIFF; 1=PSR, 0=non-PSR)
               Generated by main.py Step 2 (rasterize_psr_shapefile).
               Must be co-registered with the DEM (same shape, CRS, transform).

PSR_SHP_PATH : Path — PSR shapefile (fallback if TIF not available)
               LOLA-derived PSR polygons (Mazarico et al. 2011 or similar).

Outputs
-------
psr_mask  : np.ndarray, uint8, shape (H, W), C-contiguous
            1 = pixel is inside a Permanently Shadowed Region
            0 = pixel is not in a PSR (can be illuminated at some time)
psr_rows  : np.ndarray, int32, shape (P,) — row indices of PSR pixels
psr_cols  : np.ndarray, int32, shape (P,) — col indices of PSR pixels

Mathematical basis
------------------
No computation.  Binary lookup: psr_mask[row, col] ∈ {0, 1}.
Extraction of indices uses np.where (single C-level pass, O(H×W)).

Time complexity  : O(H × W)  —  load + index extraction
Memory complexity: O(H × W)  —  ~15 168² × 1 byte ≈ 230 MB for uint8
                  O(P)        —  ~20 M int32 indices ≈ 80 MB (typical)

Optimisation strategy
---------------------
• uint8 dtype (not bool) avoids type-conversion overhead in Numba kernel,
  which reads psr[r, c] == 0 directly as an integer comparison.
• np.ascontiguousarray ensures the Numba kernel's row access is cache-friendly.
• Indices are int32 (not int64) to halve memory and improve cache performance
  in the PSR pixel scatter operation.

Reference
---------
O'Brien & Byrne (2022), PSJ 3:258, Section 2.1 (PSR definition).
Mazarico et al. (2011), JGR Planets, 116, E00H08 (LOLA PSR mapping).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

import numpy as np
import rasterio
from rasterio.features import rasterize

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from dpsr.utils import PSR_MASK_TIF, PSR_SHP_PATH, get_logger

log = get_logger(__name__)


def load_psr_mask(
    psr_tif_path: Path = PSR_MASK_TIF,
    psr_shp_path: Optional[Path] = PSR_SHP_PATH,
    dem_meta: Optional[dict] = None,
    dem_shape: Optional[tuple] = None,
) -> np.ndarray:
    """
    Load the binary PSR mask from a GeoTIFF or rasterise from shapefile.

    Parameters
    ----------
    psr_tif_path : Path to pre-rasterised PSR GeoTIFF (preferred).
    psr_shp_path : Path to PSR shapefile (fallback; requires dem_meta+dem_shape).
    dem_meta     : rasterio metadata from step01 (needed for shapefile rasterise).
    dem_shape    : (H, W) of the DEM (needed for shapefile rasterise).

    Returns
    -------
    psr_mask : uint8 ndarray (H, W)  1=PSR  0=non-PSR  C-contiguous

    Raises
    ------
    FileNotFoundError : if neither TIF nor shapefile is available
    ValueError        : if PSR mask shape differs from DEM shape
    """
    if psr_tif_path.exists():
        log.info("Loading pre-rasterised PSR mask from %s", psr_tif_path.name)
        with rasterio.open(psr_tif_path) as ds:
            arr = ds.read(1, out_dtype=np.uint8)
        psr_mask = np.ascontiguousarray(arr, dtype=np.uint8)

        if dem_shape is not None and psr_mask.shape != dem_shape:
            raise ValueError(
                f"PSR mask shape {psr_mask.shape} != DEM shape {dem_shape}.\n"
                "Regenerate PSR_mask.tif with: python main.py"
            )

    elif psr_shp_path is not None and psr_shp_path.exists():
        # Auto-derive DEM meta if caller did not supply it
        if dem_meta is None or dem_shape is None:
            log.info("dem_meta not supplied — loading DEM to get CRS/transform …")
            from dpsr.step01_load_dem import load_dem
            _elev, dem_meta = load_dem()
            dem_shape = _elev.shape
            del _elev
        log.info("Rasterising PSR shapefile %s …", psr_shp_path.name)
        psr_mask = _rasterize_shapefile(psr_shp_path, dem_meta, dem_shape)

        # Cache to GeoTIFF so downstream steps (step06, step07) can open it
        psr_tif_path.parent.mkdir(parents=True, exist_ok=True)
        write_meta = dem_meta.copy()
        write_meta.update(dtype="uint8", count=1, compress="lzw",
                          driver="GTiff", nodata=None)
        with rasterio.open(psr_tif_path, "w", **write_meta) as dst:
            dst.write(psr_mask, 1)
        log.info("PSR mask cached → %s  (%.1f MB)",
                 psr_tif_path.name, psr_tif_path.stat().st_size / 1e6)

    else:
        raise FileNotFoundError(
            f"No PSR mask found.\n"
            f"  Checked TIF : {psr_tif_path}\n"
            f"  Checked SHP : {psr_shp_path}\n"
            "Run 'python main.py' to generate PSR_mask.tif, or supply the shapefile."
        )

    n_psr   = int(np.count_nonzero(psr_mask))
    n_total = psr_mask.size
    log.info(
        "PSR mask loaded  shape=%s  PSR=%s px  (%.2f%% of DEM)",
        psr_mask.shape,
        f"{n_psr:,}",
        100.0 * n_psr / n_total,
    )
    return psr_mask


def _rasterize_shapefile(
    shp_path: Path,
    dem_meta: dict,
    dem_shape: tuple,
) -> np.ndarray:
    """
    Burn PSR polygon geometries onto the DEM grid.

    Parameters
    ----------
    shp_path  : Path to the PSR shapefile.
    dem_meta  : rasterio metadata dict from step01 (contains CRS and transform).
    dem_shape : (H, W) of the output raster.

    Returns
    -------
    psr_mask : uint8 ndarray (H, W), 1=inside PSR polygon, 0=outside
    """
    import geopandas as gpd

    psr = gpd.read_file(shp_path)
    dem_crs = dem_meta.get("crs")

    if psr.crs is None:
        log.warning("PSR shapefile has no CRS — assuming DEM CRS.")
        psr = psr.set_crs(dem_crs)
    elif psr.crs != dem_crs:
        log.info("Re-projecting PSR shapefile to DEM CRS …")
        psr = psr.to_crs(dem_crs)

    mask = rasterize(
        [(geom, 1) for geom in psr.geometry],
        out_shape = dem_shape,
        transform = dem_meta["transform"],
        fill      = 0,
        dtype     = "uint8",
    )
    return np.ascontiguousarray(mask, dtype=np.uint8)


def extract_psr_indices(psr_mask: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Extract row and column indices of every PSR pixel.

    Purpose   : Build the list of pixels to process in the ray-casting kernel.
                Only PSR pixels are candidates for DPSR; non-PSR pixels are skipped.
    Inputs    : psr_mask — uint8 (H, W), 1 where pixel is inside a PSR
    Outputs   : (psr_rows, psr_cols) — int32 arrays of shape (P,)
    Math      : Equivalent to argwhere(psr_mask == 1) but returns two 1-D arrays
                instead of one 2-D array, which is more cache-friendly for the
                Numba kernel's linear scatter.
    Complexity: O(H × W) — single np.where call (vectorised C loop, not Python).
    Memory    : O(P) — two int32 arrays of length P ≈ 20 M → 80 MB total.
    """
    rows, cols = np.where(psr_mask == 1)
    psr_rows   = np.ascontiguousarray(rows, dtype=np.int32)
    psr_cols   = np.ascontiguousarray(cols, dtype=np.int32)
    log.info("PSR indices extracted  count=%s", f"{len(psr_rows):,}")
    return psr_rows, psr_cols


# ---------------------------------------------------------------------------
# CLI entry point — run as: python step02_load_psr.py
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mask = load_psr_mask()
    rows, cols = extract_psr_indices(mask)
    print(f"\n  Shape      : {mask.shape}")
    print(f"  PSR pixels : {int(mask.sum()):,}")
    print(f"  PSR area   : {int(mask.sum()) * 20.0**2 / 1e6:.1f} km²")
    print(f"  PSR / DEM  : {100.0 * mask.mean():.2f}%")
    print(f"  Unique vals: {np.unique(mask).tolist()}")
